version: 2

jobs:
  build:
    branches:
      ignore:
        - development
        - /feature-.*/
        - /development-.*/
    docker:
      - image: "buildpack-deps:bionic"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing Ninja
          command: 'apt-get update && apt-get install -y ninja-build'
      - run:
          name: Installing CMake
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'cmake -G Ninja -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cd build && ninja'