version: 2

jobs:
  build:
    branches:
      ignore:
        - development
        - /feature-.*/
        - /development-.*/
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run docker image
          command: docker build -t $IMAGE_NAME:latest .
